site_name: Grupo-06
repo_url: https://github.com/Requisitos-de-Software/2023.2-Grupo06

theme:
  name: material
  features:
        - navigation.tabs

nav:
  - Início: index.md
  - Planejamento: 
    - Cronograma: planejamento/cronograma.md
    - Feramentas: planejamento/ferramentas.md
  - Atas: 
    - Reunião 00: atas/reuniao00.md
    - Reunião 01: atas/reuniao01.md