repo_name: 2023.2-Skoob
site_name: Skoob
repo_url: https://github.com/Requisitos-de-Software/2023.2-Skoob

theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Dark mode

  # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-night
        name: Light mode

  logo: planejamento/img/logos/skoob2.png
  favicon: planejamento/img/logos/skoob2.png
  
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

nav:
  - Início: index.md
  - Planejamento: 
    - Cronograma planejado: planejamento/cronograma.md
    - Cronograma executado: planejamento/cronograma_executado.md
    - Ferramentas: planejamento/ferramentas.md
    - Metodologia: planejamento/metodologia.md
    - Modelo de artefato: planejamento/modelo_artefato_apresentação.md
  - Atas: 
    - Reunião 00: atas/reuniao00.md
    - Reunião 01: atas/reuniao01.md
    - Reunião 02: atas/reuniao02.md
    - Reunião 03: atas/reuniao03.md
    - Reunião 04: atas/reuniao04.md
    - Reunião 05: atas/reuniao05.md
    - Reunião 06: atas/reuniao06.md
    - Reunião 07: atas/reuniao07.md
  - Pré-rastreabilidade: 
    - Aplicativos Analisados: pre_rastreabilidade/lista_de_aplicativos.md
    - Aplicativo Escolhido: pre_rastreabilidade/aplicativo_escolhido.md
  - Elicitação de Requisitos:
    - Requisitos Elicitados: elicitacao/requisitos.md
    - Brainstorming: elicitacao/brainstorming.md
    - Observação: elicitacao/observacao.md
    - Introspecção: elicitacao/introspeccao.md
    - First Things First: elicitacao/first_things_first.md
    - Moscow: elicitacao/moscow.md
    - Three-Level Scale: elicitacao/three_level_scale.md
    - Perfil do Usuário: elicitacao/perfil_do_usuario.md
  - Modelagem:
    - Cenários: modelagem/cenarios.md
    - Casos de uso: modelagem/casos_de_uso.md
    - Especificação Suplementar: modelagem/especificacao_suplementar.md
    - Léxicos: modelagem/lexico.md
    - NFR Framework: modelagem/nfr_framework.md
    - Backlog: modelagem/backlog.md
    - Histórias de Usuários: modelagem/user_story.md
  - Verificação:
    - Revisões: verificacao/revisoes.md
    - Grupo 6:
      - Entrega 1:
        - Cronograma Planejado: verificacao/grupo6/cronograma_6.md
        - Cronograma Executado: verificacao/grupo6/cronograma_executado_6.md
        - Ferramentas: verificacao/grupo6/ferramentas_6.md
      - Entrega 2:
        - Requisitos Elicitados: verificacao/grupo6/requisitos_6.md
      - Entrega 3:
        - Lexicos: verificacao/grupo6/lexicos_6.md
      - Entrega 4:
        - Backlog: verificacao/grupo6/backlog_6.md
      - Entrega 6: 
        - Forward-from: verificacao/grupo6/forward_6.md
        - Matriz de Rastreabilidade: verificacao/grupo6/matriz_6.md
    - Grupo 7:
      - Entrega 1: 
        - Rich Picture: verificacao/grupo7/richpicture.md
        - Aplicativos: verificacao/grupo7/aplicativos.md
        - Cronogramas: verificacao/grupo7/cronogramas.md
        - Ferramentas: verificacao/grupo7/ferramentas.md
      - Entrega 2: 
        - Análise de documentos: verificacao/grupo7/analise-documentos.md
        - Entrevista: verificacao/grupo7/entrevista.md
        - Personas: verificacao/grupo7/personas.md
        - Questionário: verificacao/grupo7/questionario.md
        - Requisitos Elicitados: verificacao/grupo7/requisitos_elicitados.md
        - First Thing First: verificacao/grupo7/FTF.md
        - Strorytelling: verificacao/grupo7/storytelling.md
        - MoSCOW: verificacao/grupo7/moscow.md
        - In or Out: verificacao/grupo7/in_or_out.md
      - Entrega 3:
        - Especificação Suplementar: verificacao/grupo7/especificacao-suplementar.md
        - Casos de uso: verificacao/grupo7/casos-de-uso.md
        - Cenários: verificacao/grupo7/cenarios.md
        - Léxico: verificacao/grupo7/lexico.md
      - Entrega 4:
        - NFR: verificacao/grupo7/nfr.md
        - Backlog do Produto: verificacao/grupo7/backlog.md
        - Histórias de Usuários: verificacao/grupo7/historias_usuarios.md
  - Pós-rastreabilidade:
    - Backward-From: pos_rastreabilidade/backward.md
    - Forward-From: pos_rastreabilidade/forward.md
    - Matriz de Rastreabilidade: pos_rastreabilidade/matriz.md
  - Entregas: planejamento/entregas.md
