repo_name: 2023.2-Skoobs
site_name: Skoob
repo_url: https://github.com/Requisitos-de-Software/2023.2-Skoob

theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Dark mode

  # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-night
        name: Light mode

  logo: planejamento/img/logos/skoob2.png
  
  name: material
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

nav:
  - Início: index.md
  - Planejamento: 
    - Cronograma planejado: planejamento/cronograma.md
    - Cronograma executado: planejamento/cronograma_executado.md
    - Feramentas: planejamento/ferramentas.md
    - Lista de Aplicativos: planejamento/lista_de_aplicativos.md
  - Atas: 
    - Reunião 00: atas/reuniao00.md
    - Reunião 01: atas/reuniao01.md
